### ISSUE TITLE
Need extra functionality in Unzip class

### ISSUE THREAD

**Issue by sergru** [fpsqdb/zip-lib#12]
It would be great if Unzip has a method to retrieve list of files either as file tree object or array of file full path names. First option is preferable.
And as complement to this method another one to extract specified list of files.

**Comment by fpsqdb** [comment]
https://github.com/fpsqdb/zip-lib?tab=readme-ov-file#unzip-and-exclude-specified-entries
```js
import * as zl from "zip-lib";

const fileList = [];
const unzip = new zl.Unzip({
    onEntry: function (event) {
        fileList.push(event.entryName);
        event.preventDefault();
    }
})
try {
    await unzip.extract("path/to/target.zip", "path/to/target");
    console.log("done", fileList);
} catch (error) {
    console.error(error);
}
```
As a workaround, this will retrieve the list of files in the zip without unzipping it.

**Comment by sergru** [comment]
OK. Thanks!
