### ISSUE TITLE
 The "original" argument must be of type Function

### ISSUE THREAD

**Issue by enentyour** [fpsqdb/zip-lib#3]
- zip-lib Version: 0.7.2
- Node.js Version: 10.6
- OS [macos, linux, windows]: windows

**Describe the bug**
 The "original" argument must be of type Function

**To Reproduce**
can you help me ?

**Comment by fpsqdb** [comment]
@enentyour Please provide the reproduction code, or you can try to upgrade node to 10.23.1.
