### ISSUE TITLE
Error: end of central directory record signature not found

### ISSUE THREAD

**Issue by codemeron1** [fpsqdb/zip-lib#5]
- zip-lib Version: 0.7.2
- Node.js Version: v14.16.1
- OS [macos, linux, windows]: Windows 10

 I encountered this error - end of central directory record signature not found when I try to unzip a zip file. The same library is used in zipping the files.

**Comment by fpsqdb** [comment]
Is it possible to provide a zip file that reproduces this problem?

Alternatively, could you provide testcase gist url to reproduce the issue?

`zip-lib` use `yazul` to unzip file. maybe you can find help from this comment.
https://github.com/thejoshwolfe/yauzl/issues/83#issuecomment-385273621
