### ISSUE TITLE
Error with Symlinks

### ISSUE THREAD

**Issue by luisdemarchi** [fpsqdb/zip-lib#7]
- zip-lib Version: 0.7.3
- Node.js Version: v15.14.0
- OS [macos, linux, windows]:  mac 12.6

**Describe the bug**
I created a symlink that its real path doesn't exist. When try to compress the folder where the link is then an error that the directory does not exist is displayed

**To Reproduce**
1.  I created a symbolic link with the help of a library.
lib: npm install lnk@1.1.0
```
await lnk('/opt/nodejs/node_modules', `./.serverless/`, { rename: 'node_modules', type: 'symbolic'});
```

2. Then I tried to zip the folder
```
 const zip = new zl.Zip({ followSymlinks: false });
    zip.addFolder(`./.serverless`);
  
    await zip.archive(`./test/${filename}`);
```

4. Error with non-existent directory

> [Error: ENOENT: no such file or directory, stat '.serverless/node_modules'] {
>   errno: -2,
>   code: 'ENOENT',
>   syscall: 'stat',
>   path: '.serverless/node_modules'
> }

I expected it to simply add the symbolic file inside the zip, without trying to resolve its actual folder

**Comment by fpsqdb** [comment]
@luisdemarchi I feel like this is the correct behavior, I've tested it with 7zip and it also fails to compress when the target doesn't exist

**Comment by luisdemarchi** [comment]
@fpsqdb I understood. I got the solution with another library. If you want to look: https://github.com/luisdemarchi/serverless-esm-layer/blob/main/index.js
