### ISSUE TITLE
follow Symlinks bug

### ISSUE THREAD

**Issue by adminy** [fpsqdb/zip-lib#9]
https://github.com/fpsqdb/zip-lib/blob/d9e247db365b169dd961e1b92f217cbac1567cca/src/zip.ts#L229-L240

This is a bug as options is never assigned to the class inside the constructor.

Also Another bug I discovered, is that there is no way to set current working directory, 

so basically you can add a bunch of files that don't exist and when you try to archive them you get back a bunch of errors since they're not relative to the process but rather relative to the path you are in. Specifying cwd parameter is a must! especially working with files.

**Comment by fpsqdb** [comment]
@adminy 
1. options is assigned to the class using typescript parameter properties feature.
  https://www.typescriptlang.org/docs/handbook/2/classes.html#parameter-properties
```typescript
    constructor(private options?: IZipOptions) {
        super();
        this.zipFiles = [];
        this.zipFolders = [];
    }
```
2. It is recommended to use absolute paths when adding file/folder.
